#!/usr/bin/env python3
"""Export Tonal using Android's 108dp launcher template.

Requires Python 3, Pillow and rsvg-convert. Pass --install to copy resources
into the phone and watchface modules. Source: icon-l-tonal.svg.
"""

import argparse
import copy
import io
from pathlib import Path
import shutil
import subprocess
import xml.etree.ElementTree as ET
import zipfile

from PIL import Image, ImageDraw, ImageFont, PngImagePlugin


ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / "artwork"
OUT = ART / "android-icons"
SVG_NS = "http://www.w3.org/2000/svg"
NS = {"svg": SVG_NS}
ET.register_namespace("", SVG_NS)
DENSITIES = {"ldpi": .75, "mdpi": 1, "hdpi": 1.5, "xhdpi": 2, "xxhdpi": 3, "xxxhdpi": 4}
# Tonal's exact path bounds (including the quadratic curve at the right edge).
BOUNDS = (150, 124, 377.090909091, 382)
SCALE = 50 / (BOUNDS[3] - BOUNDS[1])
SHIFT = 54 - 256 * SCALE


def write(path, content):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def save_png(image, path):
    path.parent.mkdir(parents=True, exist_ok=True)
    metadata = PngImagePlugin.PngInfo()
    metadata.add(b"sRGB", b"\x00")
    image.convert("RGBA").save(path, pnginfo=metadata, optimize=True)


def render(svg, size):
    result = subprocess.run(
        ["rsvg-convert", "-w", str(size), "-h", str(size)],
        input=svg.encode(), capture_output=True, check=True,
    )
    return Image.open(io.BytesIO(result.stdout)).convert("RGBA")


def svg_document(content, viewbox="0 0 108 108", size=108):
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="{SVG_NS}" width="{size}" height="{size}" viewBox="{viewbox}">
{content}
</svg>
'''


def gradient_geometry(element, bounds):
    x0, y0, x1, y1 = bounds
    return (
        x0 + float(element.get("x1", "0")) * (x1-x0),
        y0 + float(element.get("y1", "0")) * (y1-y0),
        x0 + float(element.get("x2", "1")) * (x1-x0),
        y0 + float(element.get("y2", "0")) * (y1-y0),
    )


def svg_gradient(element, bounds):
    element = copy.deepcopy(element)
    x1, y1, x2, y2 = gradient_geometry(element, bounds)
    element.set("gradientUnits", "userSpaceOnUse")
    for key, value in zip(("x1", "y1", "x2", "y2"), (x1, y1, x2, y2)):
        element.set(key, f"{value:.9f}")
    return ET.tostring(element, encoding="unicode")


def android_gradient(element, bounds):
    x1, y1, x2, y2 = gradient_geometry(element, bounds)
    stops = "\n".join(
        f'                    <item android:offset="{stop.get("offset", "0")}" android:color="{stop.get("stop-color")}" />'
        for stop in element.findall("svg:stop", NS)
    )
    return f'''            <aapt:attr name="android:fillColor">
                <gradient android:type="linear"
                    android:startX="{x1:.9f}" android:startY="{y1:.9f}"
                    android:endX="{x2:.9f}" android:endY="{y2:.9f}">
{stops}
                </gradient>
            </aapt:attr>'''


def vector(content, size=108):
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by artwork/generate_android_icons.py from icon-l-tonal.svg. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="{size}dp" android:height="{size}dp"
    android:viewportWidth="{size}" android:viewportHeight="{size}">
{content}
</vector>
'''


def mask(size, shape):
    image = Image.new("L", (size*4, size*4), 0)
    draw = ImageDraw.Draw(image)
    box = (0, 0, size*4-1, size*4-1)
    if shape == "circle":
        draw.ellipse(box, fill=255)
    elif shape == "rounded":
        draw.rounded_rectangle(box, radius=size*4*.3, fill=255)
    elif shape == "squircle":
        import math
        radius = (size*4-1)/2
        points = []
        for i in range(720):
            angle = i*math.tau/720
            x, y = math.cos(angle), math.sin(angle)
            points.append((radius+radius*math.copysign(abs(x)**.5, x),
                           radius+radius*math.copysign(abs(y)**.5, y)))
        draw.polygon(points, fill=255)
    elif shape == "teardrop":
        draw.ellipse(box, fill=255)
        draw.rectangle((size*2, size*2, size*4-1, size*4-1), fill=255)
    else:
        draw.rectangle(box, fill=255)
    return image.resize((size, size), Image.Resampling.LANCZOS)


def masked(image, shape):
    image = image.copy()
    image.putalpha(mask(image.width, shape))
    return image


def make_overview():
    board = Image.new("RGBA", (1120, 870), "#f3f3ed")
    draw = ImageDraw.Draw(board)
    font = str(ROOT / "watchface/src/main/res/font/robotoslab.ttf")
    title = ImageFont.truetype(font, 30)
    label = ImageFont.truetype(font, 17)
    small = ImageFont.truetype(font, 13)
    draw.text((40, 24), "Tonal / Android icon set", font=title, fill="#273329")
    items = [("play-store.png", "Play Store · 512px"),
             ("previews/circle.png", "Adaptive · round"),
             ("previews/squircle.png", "Adaptive · squircle"),
             ("previews/teardrop.png", "Adaptive · teardrop"),
             ("previews/themed-light.png", "Themed · light"),
             ("previews/themed-dark.png", "Themed · dark"),
             ("layers/xxhdpi/foreground.png", "Foreground · 108dp"),
             ("layers/xxhdpi/monochrome.png", "Monochrome · 108dp")]
    for index, (filename, caption) in enumerate(items):
        x, y = 40+(index%4)*274, 86+(index//4)*270
        image = Image.open(OUT / filename).convert("RGBA").resize((216,216), Image.Resampling.LANCZOS)
        if index >= 6:
            for row in range(12):
                for col in range(12):
                    color = "#7c887e" if (row+col)%2 else "#8a958d"
                    draw.rectangle((x+col*18, y+row*18, x+(col+1)*18-1, y+(row+1)*18-1), fill=color)
        board.alpha_composite(image, (x,y))
        draw.text((x,y+232), caption, font=label, fill="#42533f")
    draw.text((40, 664), "Legacy density exports", font=label, fill="#273329")
    for index, (density, factor) in enumerate(DENSITIES.items()):
        x = 40+index*180
        size = round(48*factor)
        # Show lower resolutions at native size; cap the largest to fit the sheet.
        shown = min(size, 112)
        image = Image.open(OUT / "res" / f"mipmap-{density}/ic_launcher.png").convert("RGBA")
        board.alpha_composite(image.resize((shown,shown), Image.Resampling.LANCZOS), (x,714+112-shown))
        draw.text((x, 838), f"{density} / {size}px", font=small, fill="#42533f")
    save_png(board, OUT / "preview.png")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--install", action="store_true")
    args = parser.parse_args()
    source = ET.parse(ART / "icon-l-tonal.svg").getroot()
    path = source.find("svg:path[@id='monogram']", NS).get("d")
    ink = source.find("svg:defs/svg:linearGradient[@id='ink']", NS)
    citron = source.find("svg:defs/svg:linearGradient[@id='citron']", NS)
    transform = f'translate({SHIFT:.9f} {SHIFT:.9f}) scale({SCALE:.9f})'
    foreground = f'<g transform="{transform}"><path fill="url(#ink)" d="{path}"/></g>'
    monochrome = f'<g transform="{transform}"><path fill="#ffffff" d="{path}"/></g>'
    background = '<rect width="108" height="108" fill="url(#citron)"/>'
    ink_definition = svg_gradient(ink, BOUNDS)
    background_definition = svg_gradient(citron, (18, 18, 90, 90))
    definitions = f'<defs>{ink_definition}{background_definition}</defs>'
    layers = {
        "foreground": svg_document(f'<defs>{ink_definition}</defs>{foreground}'),
        "background": svg_document(f'<defs>{background_definition}</defs>{background}'),
        "monochrome": svg_document(monochrome),
    }
    for name, content in layers.items():
        write(OUT / "svg" / f"ic_launcher_{name}.svg", content)

    # The visible 72dp viewport is cropped from the middle of the 108dp layers.
    visible = svg_document(definitions+background+foreground, "18 18 72 72", 512)
    write(OUT / "svg" / "launcher-composite.svg", visible)
    write(OUT / "svg" / "adaptive-template.svg", svg_document(
        definitions+background+foreground+'''
<g fill="none" stroke-width="0.4">
  <rect x="18" y="18" width="72" height="72" stroke="#3860b0"/>
  <circle cx="54" cy="54" r="33" stroke="#bf3b7d" stroke-dasharray="1.5 1"/>
  <path d="M54 0V108M0 54H108" stroke="#3860b0" stroke-opacity="0.5"/>
</g>''', size=864))

    res = OUT / "res"
    group = f'android:scaleX="{SCALE:.9f}" android:scaleY="{SCALE:.9f}" android:translateX="{SHIFT:.9f}" android:translateY="{SHIFT:.9f}"'
    write(res / "drawable/ic_launcher_foreground.xml", vector(f'''    <group {group}>
        <path android:pathData="{path}">
{android_gradient(ink, BOUNDS)}
        </path>
    </group>'''))
    write(res / "drawable/ic_launcher_background.xml", vector(f'''    <path android:pathData="M0,0H108V108H0Z">
{android_gradient(citron, (18, 18, 90, 90))}
    </path>'''))
    write(res / "drawable/ic_launcher_monochrome.xml", vector(f'''    <group {group}>
        <path android:fillColor="#FFFFFFFF" android:pathData="{path}" />
    </group>'''))
    adaptive = '''<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
'''
    for name in ("ic_launcher", "ic_launcher_round"):
        write(res / "mipmap-anydpi-v26" / f"{name}.xml", adaptive)

    large = render(visible, 1536)
    for density, factor in DENSITIES.items():
        size = round(48*factor)
        small = large.resize((size, size), Image.Resampling.LANCZOS)
        save_png(masked(small, "rounded"), res / f"mipmap-{density}/ic_launcher.png")
        save_png(masked(small, "circle"), res / f"mipmap-{density}/ic_launcher_round.png")
        for name, svg in layers.items():
            save_png(render(svg, round(108*factor)), OUT / "layers" / density / f"{name}.png")

    # Preserve the approved store composition; launcher sizing follows Android keylines.
    save_png(render((ART / "icon-l-tonal.svg").read_text(), 512), OUT / "play-store.png")
    shutil.copyfile(ART / "icon-l-tonal.svg", OUT / "svg" / "play-store.svg")
    for shape in ("square", "rounded", "circle", "squircle", "teardrop"):
        save_png(masked(large.resize((512,512), Image.Resampling.LANCZOS), shape), OUT / "previews" / f"{shape}.png")
    for name, bg, fg in (("themed-light", "#d7e8ca", "#3f512f"), ("themed-dark", "#293c27", "#d2e7bf")):
        themed = svg_document(f'<rect width="108" height="108" fill="{bg}"/>'+monochrome.replace("#ffffff", fg), "18 18 72 72", 512)
        save_png(masked(render(themed, 512), "circle"), OUT / "previews" / f"{name}.png")

    # Notification artwork is supplied separately; the existing service icon is unchanged.
    scale = 20 / (BOUNDS[3]-BOUNDS[1])
    shift = 12-256*scale
    notification = svg_document(f'<g transform="translate({shift:.9f} {shift:.9f}) scale({scale:.9f})"><path fill="#ffffff" d="{path}"/></g>', "0 0 24 24", 24)
    write(OUT / "notification" / "ic_stat_literary_clock.svg", notification)
    write(OUT / "notification" / "drawable/ic_stat_literary_clock.xml", vector(f'''    <group android:scaleX="{scale:.9f}" android:scaleY="{scale:.9f}" android:translateX="{shift:.9f}" android:translateY="{shift:.9f}">
        <path android:fillColor="#FFFFFFFF" android:pathData="{path}" />
    </group>''', size=24))
    for density, factor in DENSITIES.items():
        save_png(render(notification, round(24*factor)), OUT / "notification" / f"drawable-{density}/ic_stat_literary_clock.png")

    # Check the actual rendered alpha against the conservative 66dp safe circle.
    safe = render(layers["monochrome"], 1080).getchannel("A")
    pixels = safe.load()
    max_radius = max(((x+.5-540)**2+(y+.5-540)**2)**.5/10
                     for y in range(1080) for x in range(1080) if pixels[x,y]>127)
    if max_radius > 33:
        raise ValueError(f"Foreground exceeds adaptive safe circle: {max_radius:.2f}dp")
    print(f"Adaptive mark: 50dp high, maximum radius {max_radius:.2f}dp (safe radius 33dp).")

    if args.install:
        for module in ("app", "watchface"):
            destination = ROOT / module / "src/main/res"
            for file in sorted(res.rglob("*")):
                if file.is_file():
                    target = destination / file.relative_to(res)
                    target.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copyfile(file, target)
        print("Installed launcher resources in app and watchface.")

    make_overview()
    archive = ART / "tonal-android-icons.zip"
    with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED) as zipped:
        for file in sorted(OUT.rglob("*")):
            if file.is_file():
                zipped.write(file, "tonal-android-icons/"+str(file.relative_to(OUT)))
    print(f"Generated {len(list(OUT.rglob('*.*')))} assets in {OUT.relative_to(ROOT)} and {archive.name}.")


if __name__ == "__main__":
    main()
