const val KOTLIN_VERSION = "1.3.10"
const val KOTLIN_COROUTINES_VERSION = "1.0.1"
const val KOTLIN_MOCKITO_VERSION = "2.0.0-RC1"
const val KLUENT_VERSION = "1.43"
const val JUNIT_VERSION = "4.12"

const val KODEIN_VERSION = "5.3.0"

const val ARTEMCHEP_CONFIG_VERSION = "2.1.0"

const val SOLOVYEV_CHECKOUT_VERSION = "1.2.1"

const val HDODENHOF_CIRCLEIMAGEVIEW_VERSION = "2.2.0"

const val THEBLUEALLIANCE_SPECTRUM_VERSION = "0.7.1"

const val ANDROIDX_APPCOMPAT_VERSION = "1.0.2"
const val ANDROIDX_KTX_VERSION = "1.0.1"
const val ANDROIDX_BROWSER_VERSION = "1.0.0"
const val ANDROIDX_LIFECYCLE_VERSION = "2.0.0"
const val ANDROIDX_CONSTRAINTLAYOUT_VERSION = "2.0.0-alpha2"
const val ANDROIDARCH_NAVIGATION_VERSION = "1.0.0-alpha07"
const val ANDROIDARCH_WORK_VERSION = "1.0.0-alpha11"

const val GOOGLE_MATERIAL_VERSION = "1.0.0"

const val GOOGLE_FIREBASE_CORE = "16.0.6"
const val GOOGLE_FIREBASE_FIRESTORE = "17.1.5"

