name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - name: "Set up JDK 17"
        id: setup-java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Copy google-services.json
        run: |
          cd app
          echo ${{ secrets.GOOGLE_SERVICES }} | base64 -d | zcat >> google-services.json
          cd ..
      - name: "./gradlew clean bundleProdRelease assembleProdRelease"
        uses: eskatos/gradle-command-action@v2
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.path }}
        with:
          arguments: assembleProdDebug
